"""initial schema

Revision ID: 9c0fef947969
Revises: 
Create Date: 2026-06-13 22:10:43.541556
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '9c0fef947969'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_type', sa.Enum('user', 'agent', 'system', name='actor_type'), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('vm_id', sa.Uuid(), nullable=True),
    sa.Column('action_name', sa.String(length=64), nullable=True),
    sa.Column('command', sa.String(length=4096), nullable=True),
    sa.Column('result_status', sa.String(length=64), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('source_ip', sa.String(length=64), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('row_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('row_hash')
    )
    op.create_index(op.f('ix_audit_log_event_type'), 'audit_log', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_log_ts'), 'audit_log', ['ts'], unique=False)
    op.create_index(op.f('ix_audit_log_vm_id'), 'audit_log', ['vm_id'], unique=False)
    op.create_table('enrollment_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('uses_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrollment_tokens_token_hash'), 'enrollment_tokens', ['token_hash'], unique=True)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_worker_version', sa.String(length=64), nullable=False),
    sa.Column('target_release_repo', sa.String(length=255), nullable=False),
    sa.Column('allowed_release_domains', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vm_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('action', 'command', 'update', name='task_type'), nullable=False),
    sa.Column('action_name', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'dispatched', 'running', 'succeeded', 'failed', 'timeout', 'dead_letter', 'cancelled', name='task_status'), nullable=False),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('stderr', sa.Text(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_idempotency_key'), 'tasks', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_vm_id'), 'tasks', ['vm_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('oidc_subject', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('admin', 'readonly', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_oidc_subject'), 'users', ['oidc_subject'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('vms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('arch', sa.Enum('amd64', 'arm64', name='worker_arch'), nullable=False),
    sa.Column('os_info', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('state', sa.Enum('pending', 'active', 'offline', 'revoked', name='vm_state'), nullable=False),
    sa.Column('exec_mode', sa.Enum('whitelist', 'unrestricted', name='exec_mode'), nullable=False),
    sa.Column('worker_version', sa.String(length=64), nullable=True),
    sa.Column('worker_secret_hash', sa.String(length=128), nullable=True),
    sa.Column('enrollment_token_id', sa.Uuid(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vms_state'), 'vms', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vms_state'), table_name='vms')
    op.drop_table('vms')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_oidc_subject'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tasks_vm_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_idempotency_key'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('settings')
    op.drop_index(op.f('ix_enrollment_tokens_token_hash'), table_name='enrollment_tokens')
    op.drop_table('enrollment_tokens')
    op.drop_index(op.f('ix_audit_log_vm_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_ts'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_event_type'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###

    # Drop the ENUM types created implicitly by the tables above (PostgreSQL only).
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        for enum_name in (
            "exec_mode",
            "vm_state",
            "worker_arch",
            "task_status",
            "task_type",
            "actor_type",
            "user_role",
        ):
            sa.Enum(name=enum_name).drop(bind, checkfirst=True)
